### ISSUE TITLE
Some commit lines have the same color as the background (or otherwise aren't drawn)

### ISSUE THREAD

**Issue by benknoble** [dracula/gitk#1]
Screenshot provided
![gitk](https://user-images.githubusercontent.com/22802209/38781095-a41e38d6-40e0-11e8-8261-7f3f240b70d0.png)

**Comment by lourot** [comment]
Good catch, thanks, I never noticed! This fixes it for me:
```
-set colors {#50fa7b #ff5555 #bd93f9 #ff79c6 #282a36 #ffb86c #ffb86c}
+set colors {#50fa7b #ff5555 #bd93f9 #ff79c6 #f8f8f8 #ffb86c #ffb86c}
```

Do you confirm?

**Comment by benknoble** [comment]
@AurelienLourot that did it for me! Thanks.
