### ISSUE TITLE
Background colour of new & old lines in the diff not set by theme

### ISSUE THREAD

**Issue by cueman** [dracula/gitk#12]
The theme does not set the background colour for lines in the diff view. In a dark mode, the background of new lines is particularly jarring. This is what it looks like.

![gitk-without-colours](https://user-images.githubusercontent.com/742577/211801636-00fa7905-ded2-4743-b168-e2775924bf16.png)

This can be changed by adding lines like this (with colours to your taste) in the config file ~/.config/git/gitk:
> set diffbgcolors {#443333 #334433}

which would produce something like this:
![gitk-with-colours](https://user-images.githubusercontent.com/742577/211802065-540d9fe0-113e-4704-8c27-b0331572bce3.png)

**Comment by lourot** [comment]
Thanks @cueman, I think this has been fixed by https://github.com/dracula/gitk/pull/5 . Are you still having this issue?
