### ISSUE TITLE
Theme does not change certain UI elements on Windows 10 as shown in the picture

### ISSUE THREAD

**Issue by Vpatel541** [dracula/gitk#13]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.
The elements that are gray in the picture are still white

**Comment by lourot** [comment]
Thanks @Vpatel541, I don't see a screenshot? Is this related to #2 maybe?

**Comment by lmtapia** [comment]
![image](https://github.com/dracula/gitk/assets/46499990/804e005f-e55b-4c2b-9103-b65e12a7bdd8)
Any update?
