### ISSUE TITLE
Some buttons appear washed out

### ISSUE THREAD

**Issue by rfabbri** [dracula/gitk#15]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.

<img width="341" alt="Screen Shot 2023-12-07 at 16 25 16" src="https://github.com/dracula/gitk/assets/135092/6ed967e3-8796-4e78-850a-4dfcb03e95a1">
<img width="639" alt="Screen Shot 2023-12-07 at 16 25 41" src="https://github.com/dracula/gitk/assets/135092/d76bfe0c-a450-45f2-afb9-0544b7d7953c">

The text on some buttons is not being properly displayed.

This happens on Mac OS 12.6.6.

If I cmd-tab to another application, but uncover gitk, then the button text becomes visible.
gitk installed via macports

**Comment by lourot** [comment]
Thanks for reporting! I could use some help here from someone else because I don't have a mac.

Out of curiosity: are thing better/worse if you set `set want_ttk 1` in the config?

**Comment by rfabbri** [comment]
Yes, things get better overall. The UI feels more responsive as well (eg, to window resizes).
The changes are that the buttons that were light before are now also dark.
And there is a white / light-gray frame around every sub-window / viewport.
The scrollbar is now also darker.

<img width="296" alt="Screen Shot 2023-12-12 at 13 34 50" src="https://github.com/dracula/gitk/assets/135092/40cca458-e64c-4be8-9760-476af709aed2">
<img width="458" alt="Screen Shot 2023-12-12 at 13 35 32" src="https://github.com/dracula/gitk/assets/135092/cdb7e92f-631b-43fb-a044-2469ba537eea">
<img width="139" alt="Screen Shot 2023-12-12 at 13 38 13" src="https://github.com/dracula/gitk/assets/135092/71d1bb48-5f44-4db3-abd2-8c3daa0966cd">

Thanks for this consistent and beautiful gitk dark theme.

**Comment by lourot** [comment]
Thank you for the screenshots and glad it helped.

It's a pity that some setups require `set want_ttk 1` and other `set want_ttk 0`. See also #11
