### ISSUE TITLE
Incorrect colors in macOS Mojave with Dark Mode enabled

### ISSUE THREAD

**Issue by lassana** [dracula/gitk#3]
Some texts are unreadable, some button icons are missing. I suspect it isn't possible to configure buttons and drop-down pickers, but it would be nice to change the black font in a few other places.

Dracula:
![screen shot 2018-12-09 at 3 17 51 pm](https://user-images.githubusercontent.com/2004960/49697218-a75fc280-fbc5-11e8-91fb-ffcaf1b93ae9.png)

Default:
![screen shot 2018-12-09 at 3 21 16 pm](https://user-images.githubusercontent.com/2004960/49697256-189f7580-fbc6-11e8-8a8f-7a3dc118e16d.png)

- gitk-dracula `b4ffd28`
- macOS 10.14.1
- git 2.19.2

**Comment by ryanjwessel** [comment]
I'm experiencing the same issue. I'm slowly tinkering with the palette, but haven't come to an adequate solution yet. Also, all of the items in the right-click menu are invisible unless you hover over them.

**Comment by lassana** [comment]
@rynjwssl this probably requires patching Git to target 10.14 since `gitk` is run in kind of compatibility mode at the moment.
I haven't tried, though.

**Comment by lassana** [comment]
It works much better with the latest master and Git 2.29.2:
<img width="1162" alt="Screen Shot 2020-11-21 at 16 16 26" src="https://user-images.githubusercontent.com/2004960/99878250-23b60980-2c15-11eb-8795-40ce9259cb8f.png">
