### ISSUE TITLE
Error when trying to resize

### ISSUE THREAD

**Issue by gkotian** [dracula/gitk#6]
When I try to drag the horizontal bar in the middle to resize the top/bottom panes, I get the following error:
```
expected integer but got ""
expected integer but got ""
    while executing
"$win sash place 0 $sash0 [lindex $s0 1]"
    (procedure "resizeclistpanes" line 38)
    invoked from within
"resizeclistpanes .tf.histframe.pwclist 1903"
    (command bound to event)
```

I'm using Arch Linux, and my git version is `2.30.1`.
Any idea how to fix this?

Here's a screenshot:
![screenshot](https://user-images.githubusercontent.com/1580240/108637130-896e9780-7489-11eb-99cd-cec51d66eaf2.png)

**Comment by fedorenchik** [comment]
I have the same error. (I'm on Manjaro)

**Comment by smith-j-travis** [comment]
Changing

set want_ttk 0
to 
set want_ttk 1

seems to have fixed the issue for me

**Comment by gkotian** [comment]
Yes, using `set want_ttk 1` allows for resizing the top & bottom panes, but badly messes up the look of the theme :disappointed:

Here are some screenshots for comparison.

With `set want_ttk 0`:
![want_ttk_0](https://user-images.githubusercontent.com/1580240/113124670-0b36ab00-9216-11eb-9a37-29ffcb936982.png)

-----------------

With `set want_ttk 1`:
![want_ttk_1](https://user-images.githubusercontent.com/1580240/113124702-1558a980-9216-11eb-9738-a91d6c3f5e56.png)

**Comment by mdelapenya** [comment]
Setting `want_ttk 0` fixed the issue to me

**Comment by suratovvlad** [comment]
I have the same issue with Fedora 34

**Comment by senhalil** [comment]
I think I have a fix for this issue (at least on local with the fix my `gitk` doesn't return `expected integer but got ""` during resize). 

I opened the following [pull-request](https://github.com/git/git/pull/1219) :crossed_fingers: hopefully this annoyance will soon be over. 

If anyone here is a [gitgitgadget/](https://github.com/gitgitgadget/) user and "allow" my PR, it would be awesome.

**Comment by gkotian** [comment]
Thanks @senhalil for the fix. I confirmed that it works, and also left a comment on the PR. No idea what's holding it up though.

**Comment by gkotian** [comment]
Closing as https://github.com/git/git/pull/1219 has been accepted. The world will soon have an awesome gitk again! :tada:
