### ISSUE TITLE
Add `.gitattributes` file to prevent user from downloading useless files 

### ISSUE THREAD

**Issue by micalevisk** [dracula/gitk#7]
Hey!

By now, when we click on `GitHub .zip download` hyperlink we download a bunch of files that we won't use in the end. Thus I think it would be nice to remove them when downloading by using [the `export-ignore` attribute](https://git-scm.com/docs/gitattributes#_export_ignore)

| before (81.1kB) :heavy_multiplication_x: | after (1.5kB) :heavy_check_mark: |
|--------------------|---------------|
![before the change I've proposed](https://user-images.githubusercontent.com/13461315/113493513-d5abef00-94ad-11eb-98f0-e3e9f9d90701.png) | ![after](https://user-images.githubusercontent.com/13461315/113493623-f163c500-94ae-11eb-8a96-e4f4d54a5294.png)

You just need to add the following file in the project's root:

<details>
<summary><code>.gitattributes</code></summary>

```gitattributes
## Path-based git attributes
## https://www.kernel.org/pub/software/scm/git/docs/gitattributes.html
## The following files won't be added to archived files:  
/backlinks.txt      export-ignore
/LICENSE            export-ignore
/.gitattributes     export-ignore
/.github            export-ignore 
/README.md          export-ignore 
/screenshot.png     export-ignore 
```

</details>

it's pretty simple so why not? :smile: 

---

Inspired by [this article](https://medium.com/desenvolvendo-com-paixao/otimize-seu-reposit%C3%B3rio-git-utilizando-o-arquivo-gitattributes-82a23517dcd0) by @joaorobertopb

**Comment by lourot** [comment]
Thanks @micalevisk, good idea, done :)
